### ISSUE TITLE
NeteaseCloudMusicApi中返回数据有文档吗？

### ISSUE THREAD

**Issue by Niceies** [masterxing/flutter_cloud_music#2]
我想自己实现[NeteaseCloudMusicApi](https://github.com/Binaryify/NeteaseCloudMusicApi)接口里面的功能，但是我看到文档只有调用例子，并没有返回数据的描述，你在开发的过程中是先调用后才能知道返回数据格式时候再去做数据渲染吗？

**Comment by AIYO77** [comment]
> 我想自己实现[NeteaseCloudMusicApi](https://github.com/Binaryify/NeteaseCloudMusicApi)接口里面的功能，但是我看到文档只有调用例子，并没有返回数据的描述，你在开发的过程中是先调用后才能知道返回数据格式时候再去做数据渲染吗？

是的
